#!/usr/bin/env bash
# displays numbers from 1 to 20.

num=1
while [ $num -lt 21 ]
do
  echo "$num"
  case $num in
  "4") echo "bad luck from China";;
  "9") echo "bad luck form Japan";;
  "17") echo "bad luck from Italy";;
  esac
    (( num++ ))
done